{% set data = load_setup_py_data() %}

package:
  name: conda-token
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  noarch: generic

requirements:
  host:
    - python
    - pip
  run:
    - conda >=24
    - conda-content-trust
    - packaging
    - anaconda-auth >=0.10.0

test:
  imports:
    - anaconda_auth

about:
  home: https://github.com/anaconda/conda-token
  summary: Set repository access token
  license: {{ data.get('license') }}
  license_file: LICENSE
