{% set data = load_setup_py_data() %}

package:
  name: conda-token
  version: {{ data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - conda >=24
    - anaconda-auth >=0.10.0

test:
  imports:
    - anaconda_auth
    - conda_token

about:
  home: https://github.com/anaconda/conda-token
  summary: Set repository access token
  license: {{ data.get('license') }}
  license_file: LICENSE
