{% set data = load_setup_py_data() %}

package:
  name: conda-token
  version: 0.6.0
# version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  noarch: generic

requirements:
  host:
    - python
    - pip
  run:
    # includes non-setuptools != dependency
    - conda >=4.6,!=23.10.0,!=23.11.0
    - conda-content-trust
    - packaging
    - python >=3.8
    - anaconda-auth

test:
  imports:
    - anaconda_auth

about:
  home: https://github.com/anaconda/conda-token
  summary: Set repository access token
  license: {{ data.get('license') }}
  license_file: LICENSE
