name: Build and test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  package:
    name: Build package
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3.0.4
        with:
          miniconda-version: "latest"
          activate-environment: build-conda-token
          environment-file: etc/build-environment.yml
          python-version: "3.11"
          auto-activate-base: false
      - name: Conda Build
        shell: bash -l {0}
        run: |
          conda build conda.recipe --no-test
          mv $CONDA_PREFIX/conda-bld .
  test:
    name: ${{ matrix.os }}-${{ matrix.conda-version }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.8, 3.9, "3.10", "3.12"]
        conda-version: [4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, "4.10", "4.11", "4.12", "23.9.0", "24.5.0"]
        exclude:
          # Python 3.8
          - python-version: 3.8
            conda-version: 4.3
          - python-version: 3.8
            conda-version: 4.4
          - python-version: 3.8
            conda-version: 4.5
          - python-version: 3.8
            conda-version: 4.6
          - python-version: 3.8
            conda-version: 4.7

          # Python 3.9
          - conda-version: 4.3
            python-version: 3.9
          - conda-version: 4.4
            python-version: 3.9
          - conda-version: 4.5
            python-version: 3.9
          - conda-version: 4.6
            python-version: 3.9
          - conda-version: 4.7
            python-version: 3.9
          - conda-version: 4.8
            python-version: 3.9

          # Python 3.10
          - conda-version: 4.3
            python-version: "3.10"
          - conda-version: 4.4
            python-version: "3.10"
          - conda-version: 4.5
            python-version: "3.10"
          - conda-version: 4.6
            python-version: "3.10"
          - conda-version: 4.7
            python-version: "3.10"
          - conda-version: 4.8
            python-version: "3.10"
          - conda-version: 4.9
            python-version: "3.10"
          - conda-version: "4.11"
            python-version: "3.10"
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Download conda standalone
        shell: bash
        run: |
          if [ $RUNNER_OS == 'Linux' ]; then
            curl https://repo.anaconda.com/pkgs/misc/conda-execs/conda-4.10.3-linux-64.exe -o conda.exe
          elif [ $RUNNER_OS == 'Windows' ]; then
            curl https://repo.anaconda.com/pkgs/misc/conda-execs/conda-4.10.3-win-64.exe -o conda.exe
          elif [ $RUNNER_OS == 'macOS' ]; then
            curl https://repo.anaconda.com/pkgs/misc/conda-execs/conda-4.10.3-osx-64.exe -o conda.exe
          fi
          chmod +x conda.exe
          ./conda.exe config --set auto_update_conda false
          ./conda.exe info
      - name: Setup miniconda
        shell: bash
        run: |
          ./conda.exe create -p $HOME/miniconda conda=${{ matrix.conda-version }} python=${{ matrix.python-version }} packaging pytest pytest-cov requests conda-content-trust tqdm
      - name: py.test
        env:
          CE_TOKEN: ${{ secrets.CE_TOKEN }}
          PYTHONHASHSEED: 0
        shell: bash
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            source $HOME/miniconda/Scripts/activate root && conda --version && py.test -xv
          else
            source $HOME/miniconda/bin/activate root && conda --version && py.test -xv
          fi
#     - name: Codecov
#       uses: codecov/codecov-action@v1
#       with:
#         file: ./cov.xml
#         env_vars: OS,PYTHON